### ISSUE TITLE
HDF5 for large-scale data

### ISSUE THREAD

**Issue by vodp** [gustavla/caffe-weighted-samples#1]
Hi, I found your folk useful. Just a question about the efficiency of using HDF5 data layer. Though I have not tested, I heard that HDF5 load all data into memory, so it is impractical to use in large-scale training such as the ImageNet collection. How about your opinion?

**Comment by gustavla** [comment]
Note that I keep a much more updated version of Caffe that supports sample weights here: https://github.com/gustavla/caffe/tree/gustav

This new version is a much less invasive change that achieves the same effect. The weighted loss is now achieved by specific layers that take sample weights in a separate channel. That means you can load them through any means, such as LMDB. It's also possible to load your data through LMDB and your sample weights through HDF5 (something I find convenient). You are right that HDF5 is loaded entirely into memory, but note that sample weights takes only 32 bits per sample, so 50 million samples would only take up 200 MB.

**Comment by ChenSiqin** [comment]
@gustavla Hi, gustavla! You did a great work. Now I want to implement the asymmetric loss：
![1](https://cloud.githubusercontent.com/assets/10530998/9035650/80393e76-3a0c-11e5-8ea3-677b44eacead.png)
I am wondering whether asymmetric loss can be archieved by your caffe-weighted-samples?
Thanks!
Siqin

**Comment by gustavla** [comment]
Yes, you just have to pre-compute the samples weights accordingly.

However, as I said in the comment above, I recommend my newer repository that handles the sample weights in a much more flexible way.

**Comment by ChenSiqin** [comment]
@gustavla Thanks a lot!

**Comment by ChenSiqin** [comment]
@gustavla Hi, Gustavla! I have a question about using your repository to implement the weighted loss int the caffe: I usually set the data layer's transform parameter: for example, mirror:true and crop_size: 277 in the Alexnet, which means one input image will get 10 tranformed 227x227 input images. So should the first dimension(sample number) of input sample_weight blob be 10 times greater than the first dimension(sample number) of input data or label blob? Thank you in advance!
Siqin

**Comment by gustavla** [comment]
I'm not sure off the top of my head - you'll have to test both approaches. I would recommend that you to use my newer version that I've referenced above though, since I think it might handle this better.
