### ISSUE TITLE
Make Fails

### ISSUE THREAD

**Issue by amanrajdce** [gustavla/caffe-weighted-samples#3]
I tried your latest release of caffe-weighted, i am interested in using it for imabalanced dataset
However, i get the following error while doing  `make all`
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/layers/hypercolumn_extractor.cpp
CXX tools/caffe.cpp
CXX tools/extract_features.cpp
CXX tools/upgrade_net_proto_binary.cpp
CXX tools/device_query.cpp
CXX tools/convert_imageset.cpp
CXX tools/upgrade_net_proto_text.cpp
CXX tools/train_net.cpp
CXX tools/finetune_net.cpp
CXX tools/net_speed_benchmark.cpp
CXX examples/cifar10/convert_cifar_data.cpp
CXX examples/mnist/convert_mnist_data.cpp
CXX examples/siamese/convert_mnist_siamese_data.cpp
In file included from ./include/caffe/common.hpp:19:0,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/layer.hpp:8,
                 from src/caffe/layers/hypercolumn_extractor.cpp:3:
./include/caffe/util/device_alternate.hpp:14:15: error: expected initializer before '<' token
 void classname<Dtype>::Forward_gpu(const vector<Blob<Dtype>*>& bottom, \
               ^
src/caffe/layers/hypercolumn_extractor.cpp:201:1: note: in expansion of macro 'STUB_GPU'
 STUB_GPU(HypercolumnExtractorPairsLayer);
 ^
./include/caffe/util/device_alternate.hpp:17:15: error: expected initializer before '<' token
 void classname<Dtype>::Backward_gpu(const vector<Blob<Dtype>*>& top, \
               ^
src/caffe/layers/hypercolumn_extractor.cpp:201:1: note: in expansion of macro 'STUB_GPU'
 STUB_GPU(HypercolumnExtractorPairsLayer);
 ^
make: *** [.build_release/src/caffe/layers/hypercolumn_extractor.o] Error 1
make: *** Waiting for unfinished jobs....

It breaks while compiling any layer. I guess it's a bug. Any input will be much appreciated. I am using `CPU_ONLY:=1`

**Comment by gustavla** [comment]
This is an old and abandoned branch. I offer the same functionality in this branch:

* https://github.com/gustavla/caffe

You might have to wire it up a bit differently. Check the BRANCHFEATURES.md file for details.
